name: weather_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  ansi_modifier: ^0.1.2
  args: ^2.4.2
  http: ^1.2.1
  interact: ^2.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
